### ISSUE TITLE
Arithmetic circuit library

### ISSUE THREAD

**Issue by Cryoris** [qiskit-advocate/qamp-spring-21#12]
# Description
Imagine your given the task to write a numerical program on your computer, maybe a simple one like summing certain numbers or a bit more difficult to integrate a function. Now you know an algorithm and you'll start implementing it. Are you writing bit-operations? 

No, most certainly not! You'll use fundamental arithmetic operations like `* + - / ^` or even an existing library. 

But in Quantum computing frameworks we're often restricted to really using low-level qubit operations, like the Pauli gates or the Hadamard gate. This makes writing elaborate algorithms very strenuous and you might find yourself re-implementing the same bits of code again and again. 

To allow writing algorithms more quickly and to enable re-use of modular code blocks, we've started a library of useful circuits: [Qiskit's circuit library](https://qiskit.org/documentation/apidoc/circuit_library.html). In this project, you'll add important circuits for basic arithmetic operations like addition or multiplication, including some tests to validate them.

Examples:
* Ripple-carry adder: https://arxiv.org/pdf/quant-ph/0410184.pdf
* QFT-based adder: https://arxiv.org/pdf/quant-ph/0008033.pdf
* Multiplication: https://arxiv.org/pdf/1411.5949.pdf
* and others!

# Mentor/s
Julien Gacon (@Cryoris), Pre-Doc researcher at IBM Research Zurich, Qiskit Terra and Aqua core developer

# Type of participant

You just need basic knowledge of Python and Qiskit circuits 🙂 Ideally you're familiar with some arithmetic circuits, such as the adder circuits.

# Number of participants
2

# Deliverable

Depending on how fast we move along there are different levels we can reach:

**Level 1:**

Basic arithmetic circuits (and tests) added to the circuit library:
- [ ] Adders 
- [ ] Multipliers
- [ ] (opt) Tutorial

**Level 2:**
- [ ] Piecewise Polynomials

**Level 3:**
- [ ] Inverse square root 
- [ ] Arcsine

Progress is tracked here: https://github.com/Cryoris/qiskit-terra/projects/2

**Comment by HuangJunye** [comment]
@mantcep @ManjulaGandhi Can you comment on this issue so that I can assign you? Please also work with your mentor to refine the project, define scope and deliverables and update the project description in this issue.

**Comment by Cryoris** [comment]
We synced on the project plan and I updated the description accordingly.

**Comment by ManjulaGandhi** [comment]
Thanks a lot for selecting! Would be very glad to contribute and be part of the team.

**Comment by mantcep** [comment]
Really glad to be working on this project! Thanks @Cryoris for updating the description!

**Comment by desireevl** [comment]
Hey, excited to see these implemented in Qiskit! Was just wondering if this project is similar to this? https://github.com/hkhetawat/QArithmetic

**Comment by Cryoris** [comment]
Some of the operations are the same yeah, though this projects implements them as library circuits with rigorous tests rather than as functions (also we might include some more variants) see e.g. the first part on the adders: Qiskit/qiskit-terra#6164.
