### ISSUE TITLE
Quantumized Data Types in Programming Languages 

### ISSUE THREAD

**Issue by nalraajan** [qiskit-advocate/qamp-spring-21#48]
# Description
Current programming languages have various data types to store different types of data. The storage of data is different for each data type.

Instead we have a quantum data type, that holds any types of data. Only the execution time the application choose what data it need to store. Same storage is used for any data storage. Only the application execution makes difference to retrieve the data

# Mentor/s
I can be part of Mentoring

# Type of participant
Computer science graduates, good experience in compiler, interpreter, data structure and storage techniques

# Number of participants
4

# Deliverable
New way of programming for developers. Programmers no need to mention explicitly the type of data, while programming the data type is decided and storage assigned during the course of compilation and execution.

**Comment by HuangJunye** [comment]
Closing this issue as it was not a project for QAMP Spring 21
